---
title: Creating legends when using constants for aesthetics in ggplot2
author: Ariel Muldoon
date: '2018-07-18'
slug: legends-constants-for-aesthetics-in-ggplot2
categories:
  - r
tags:
  - ggplot2
draft: TRUE
description: "Getting a legend when aesthetics are constant in a layer can be confusing.  I go through an example to show a situation where this might occur, the common mistakes, and the way to get the desired legend."
---

The general way that plotting in **ggplot2** works it that if you want to map an aesthetic to a variable and get a legend you do it inside `aes()`.  If you want to set an aesthetic to a constant,like changing the color of all points, you do it outside `aes()`.  

However, there are situations where you are going to set an aesthetic for a layer to a constant but you also want a legend.  Sometimes the "simplest" answer might be to get your dataset into a long format to better work with **ggplot2**.  I've been seeing this a lot on Stack Overflow this summer and though it worth a mini-post.

# The setup

A couple common situations where we might want legends without mapping an aesthetic to a variable are
1. Adding the mean as a line or symbol and wanting a legend to define it
2. Adding results from different fitted models

I'll focus on the latter.  I'm going to be using the ubiquitous `mtcars` dataset because it's easy. `r emo::ji("laughing")`

# Making a plot using constant aesthetics

I'll start by loading the **ggplot2** package.

```{r}
library(ggplot2) # v. 3.0.0
```

# Adding a legend by moving aesthetics into aes()

# Using scale_color_identity()

# Using scale_color_manual()


See what I would consider some of the canonical questions and answers on this from Stack Overflow [here](https://stackoverflow.com/questions/10349206/add-legend-to-ggplot2-line-plot)and [here](https://stackoverflow.com/questions/17148679/construct-a-manual-legend-for-a-complicated-plot).  (I'm sure there are others, but these are two that I've been linking to as duplicates recently. `r emo::ji("smiley_cat")`) 
