---
title: 'Simulate! Simulate! - Part 1: A linear model'
author: Ariel Muldoon
date: '2018-01-09'
slug: simulate-simulate-part1
categories: [r, statistics]
tags: [simulation, teaching]
draft: TRUE
description: "Where I discuss simulations, why I love them, and get started on a simulation series with a simple two-group linear model."
---

I have to confess:  I love simulations.  

I use simulations to check my intuition and understanding of statistical theory.  When someone tells me with great certainty "I don't need to meet that assumption for this because [fill in the blank]", I tend turn to simulations rather than textbooks.

I like simulations in the same way I like building Bayesian models and using resampling methods (i.e., Monte Carlo) for inference.  Building the simulation increases my understanding of the problem and makes all assumptions very clear.

# Simulate, simulate, dance to the music

I would like to use simulations more in teaching and consulting.  We've had a difficult time fitting in to the data analysis class I co-instruct; there's just to many other things that we have to cover in only eight weeks of instruction.


